; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INno SETUP SCRIPT FILES!

; --- Phần 1: Định nghĩa các biến chung ---
; Giúp bạn dễ dàng thay đổi thông tin ở một nơi duy nhất cho các phiên bản sau.
#define MyAppName "Task Flow"
#define MyAppVersion "2.0.0" 
#define MyAppPublisher "Luong Tran"
#define MyAppExeName "TaskFlow.exe"
#define MyAppNotifierName "notifier.exe"
#define MySetupBaseName "TaskFlow-v2.0-setup"
#define MySourcePath "C:\TaskFlowCalendarBlocking\dist\TaskFlow"
#define MyIconFile "C:\TaskFlowCalendarBlocking\TaskFlowLogo.ico"

; --- Phần 2: Cài đặt chính cho trình cài đặt ---
[Setup]
; AppId là một mã định danh duy nhất cho ứng dụng của bạn.
AppId={{7784BB34-E820-4706-A9C1-64D85CF83AD5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
UninstallDisplayIcon={app}\{#MyAppExeName}

; Yêu cầu cài đặt trên hệ điều hành 64-bit.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

; Các cài đặt về file output
OutputDir=C:\TaskFlowCalendarBlocking
OutputBaseFilename={#MySetupBaseName}
SetupIconFile={#MyIconFile}
SolidCompression=yes
WizardStyle=modern

; --- Phần 3: Ngôn ngữ ---
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

; --- Phần 4: Các tùy chọn thêm cho người dùng khi cài đặt ---
[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";
Name: "startup"; Description: "Start Task Flow Notifier on system startup"; GroupDescription: "Additional tasks:"; Flags: unchecked

; --- Phần 5: Sao chép các file ứng dụng ---
; Dòng này sao chép TẤT CẢ nội dung từ thư mục nguồn vào thư mục cài đặt.
[Files]
Source: "{#MySourcePath}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; --- Phần 6: Tạo các shortcut ---
[Icons]
; Shortcut trong Start Menu
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
; Shortcut trên Desktop (chỉ tạo nếu người dùng tick chọn)
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
; Shortcut trong thư mục Startup (chỉ tạo nếu người dùng tick chọn)
Name: "{commonstartup}\TaskFlow Notifier"; Filename: "{app}\{#MyAppNotifierName}"; Tasks: startup

; --- Phần 7: Tự động chạy sau khi cài đặt ---
; Chạy cả ứng dụng chính và dịch vụ thông báo sau khi cài đặt xong.
[Run]
Filename: "{app}\{#MyAppNotifierName}"; Description: "Launch Task Flow Notifier"; Flags: nowait postinstall skipifsilent
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent
